### ISSUE TITLE
[Issue] Nixpkgs Version Crash

### ISSUE THREAD

**Issue by linuxmobile** [NickvisionApps/Cavalier#159]
I recently installed the nixpkgs version, and apparently it crashes. When playing audio, the app crashes.

```bash
[AURA] Listening to commands.
UnhandledException - unhandled exception: System.DllNotFoundException: Unable to load shared library 'libGL.so.1' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/nix/store/xpjgbrvxy00py50p19wyqmfbxh6vr30r-cavalier-2024.1.0/lib/cavalier/libGL.so.1: cannot open shared object file: No such file or directory
/nix/store/4z363kk982cnaywc36cgcdsac7an5qif-dotnet-runtime-8.0.5/shared/Microsoft.NETCore.App/8.0.5/libGL.so.1: cannot open shared object file: No such file or directory
/nix/store/xpjgbrvxy00py50p19wyqmfbxh6vr30r-cavalier-2024.1.0/lib/cavalier/liblibGL.so.1: cannot open shared object file: No such file or directory
/nix/store/4z363kk982cnaywc36cgcdsac7an5qif-dotnet-runtime-8.0.5/shared/Microsoft.NETCore.App/8.0.5/liblibGL.so.1: cannot open shared object file: No such file or directory
/nix/store/xpjgbrvxy00py50p19wyqmfbxh6vr30r-cavalier-2024.1.0/lib/cavalier/libGL.so.1.so: cannot open shared object file: No such file or directory
/nix/store/4z363kk982cnaywc36cgcdsac7an5qif-dotnet-runtime-8.0.5/shared/Microsoft.NETCore.App/8.0.5/libGL.so.1.so: cannot open shared object file: No such file or directory
/nix/store/xpjgbrvxy00py50p19wyqmfbxh6vr30r-cavalier-2024.1.0/lib/cavalier/liblibGL.so.1.so: cannot open shared object file: No such file or directory
/nix/store/4z363kk982cnaywc36cgcdsac7an5qif-dotnet-runtime-8.0.5/shared/Microsoft.NETCore.App/8.0.5/liblibGL.so.1.so: cannot open shared object file: No such file or directory

   at NickvisionCavalier.GNOME.Views.DrawingView.glClear(UInt32 mask)
   at NickvisionCavalier.GNOME.Views.DrawingView.OnRender(GLArea sender, RenderSignalArgs e) in /build/source/NickvisionCavalier.GNOME/Views/DrawingView.cs:line 203
   at GObject.ReturningSignal`3.<>c__DisplayClass11_0.<Connect>b__0(Value returnValue, Value[] parameters)
   at GObject.Closure.InternalCallback(IntPtr closure, IntPtr returnValuePtr, UInt32 nParamValues, ValueData[] paramValuesData, IntPtr invocationHint, IntPtr userData)
```

**Comment by nlogozzo** [comment]
Well according to the error message, you are missing `libGL`.

We do not package nor maintain the nikpkg. Our only supported package formats are Flatpak, Snap, and AUR. I recommend installing Cavalier via one of those formats or contain the nikpkg maintainer.
